### ISSUE TITLE
Issue with #first_wa

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/collections_practice_vol_2#7] opened 2015-11-11 03:31 UTC
I have an issue with the fourth test in this lab that requires one to create a method that returns the first element in an array beginning with "wa". I have a method that works out in irb and here it is:

```
def first_wa(array)
  array.find do |x|
     x.start_with("wa")
  end
end
```

Yet I am met with a method error in learn, check it out:

```
1) collections practice vol 2. #first_wa Return the first element that begins with the letters 'wa'
     Failure/Error: expect(first_wa(["candy", :pepper, "wall", :ball, "wacky"])).to eq("wall")
     NoMethodError:
       undefined method `start_with?' for :pepper:Symbol
     # ./collections_practice.rb:30:in `block in first_wa'
     # ./collections_practice.rb:29:in `each'
     # ./collections_practice.rb:29:in `find'
     # ./collections_practice.rb:29:in `first_wa'
     # ./spec/collections_practice_spec.rb:118:in `block (3 levels) in <top (required)>'
```

The issue is that I have used `.start_with?` in another method in this very same lab and passed that test. What's up?

**Comment by maxwellbenton** [comment] 2019-07-17 21:51
Hi @m00se333,

Thank you for opening this issue and providing feedback. It looks from your code snippet that you may be missing the `?` at the end of `.start_with?` which is likely the cause of this error:

```
def first_wa(array)
  array.find do |x|
     x.start_with("wa")
  end
end
```

You solution looks valid otherwise. As this appears to be related to the solution, I am going to close this issue.

**Closed by maxwellbenton** 2019-07-17 21:51 UTC
